[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pymodule"
version = "0.1.0"
description = "Python module skeleton (please rename)"
readme = { text = """This is a multi-line basic string.
It allows for special characters such as \n for newlines and " for quotes.""", content-type = "text/plain" }
requires-python = ">=3.6"

# Author information using a literal single-quoted email and basic double-quoted name
authors = [
    { name = "Ivan Cenov", email = "ivan.cenov@rnd.bg" }
]
maintainers = [
    { name = "Ivan Cenov", email = "ivan.cenov@rnd.bg" }
]

# Dependencies
dependencies = [
    "numpy>=1.18.5",
    "jsonschema",
    "paho-mqtt",
    "rfc3986",
    "PyQt5"
]

# Defining various URLs (these UTL are examples, please add ture urls and/or remove redundant ones.
[project.urls]
homepage = "https://pymodule.example.com"  # Literal string for homepage URL
repository = "https://repo.pts.rnd.bg:4444/ivan.cenov/tbench.git"  # Basic string for repository URL
documentation = "https://pymodule.readthedocs.io"
bug_tracker = "https://github.com/username/pymodule/issues"
changelog = "https://github.com/username/pymodule/releases"
ci_pipeline = "https://github.com/username/pymodule/actions"
funding = "https://github.com/sponsors/username"
faq = "https://pymodule.example.com/faq"  # Custom URL key for FAQ

# Example custom configuration for `setuptools`
[tool.setuptools]
package-dir = {"" = "src"}  # Single-quoted key for directory name

[tool.setuptools.packages.find]
where = ["src"]

# Entry point for the CLI script
[project.scripts]
tbench = "cli.app:main"

